"""empty message

Revision ID: e778d260776e
Revises: None
Create Date: 2016-08-03 15:40:42.636015

"""

# revision identifiers, used by Alembic.
revision = 'e778d260776e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Class',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('time', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Power',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Role',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Lab',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('status', sa.Enum('Activated', 'Downloadable', 'Unactivated', name='status'), nullable=True),
    sa.Column('class_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['Class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role_name'], ['Role.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('association_role_power',
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.Column('power_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['power_id'], ['Power.id'], ),
    sa.ForeignKeyConstraint(['role_name'], ['Role.name'], )
    )
    op.create_table('Experiment',
    sa.Column('id', sa.String(length=192), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('value_type', sa.Enum('Number', 'Text', name='value_type'), nullable=True),
    sa.Column('value_range', sa.String(length=64), nullable=True),
    sa.Column('value_candidates', sa.String(length=512), nullable=True),
    sa.Column('lab_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['Lab.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('association_class_user',
    sa.Column('class_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['Class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    op.create_table('association_user_lab',
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('lab_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['Lab.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    op.create_table('Observation',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=320), nullable=False),
    sa.Column('student_name', sa.String(length=128), nullable=False),
    sa.Column('datum', sa.String(length=512), nullable=False),
    sa.Column('experiment_id', sa.String(length=192), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['Experiment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Observation')
    op.drop_table('association_user_lab')
    op.drop_table('association_class_user')
    op.drop_table('Experiment')
    op.drop_table('association_role_power')
    op.drop_table('User')
    op.drop_table('Lab')
    op.drop_table('Role')
    op.drop_table('Power')
    op.drop_table('Class')
    ### end Alembic commands ###
